name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          gem install bundler -v 2.0.2
          bundle install
      - name: Run rubocop
        run: bundle exec rubocop -D
      - name: Run tests
        run: bundle exec rspec
